# Generated by Django 5.0.7 on 2024-08-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smth', '0005_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='boats/'),
        ),
    ]
