# Generated by Django 5.0.7 on 2024-08-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smth', '0006_boat_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='assd/'),
        ),
    ]
