# Generated by Django 5.0.7 on 2024-08-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smth', '0007_alter_boat_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='img',
        ),
    ]
