# Generated by Django 5.0.7 on 2024-08-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smth', '0011_link'),
    ]

    operations = [
    ]
