# Generated by Django 5.0.7 on 2024-08-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smth', '0013_auto_20240821_1714'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
