# Generated by Django 5.0.7 on 2024-08-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smth', '0015_controls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='License',
        ),
    ]
